export const tags = [
  { value:'route-66', label: 'Route 66'},
  { value:'vegas', label: 'Vegas'},
  { value:'hollywood', label: 'Hollywood'},
  { value:'chicago', label: 'Chicago'},
  { value:'mountains', label: 'Mountains'},
  { value:'scenery', label: 'Scenery'},
  { value:'villages', label: 'Villages'},
  { value:'beaches', label: 'Beaches'},
  { value:'convoy', label: 'Convoy'},
  { value:'hilly', label: 'Hilly'},
  { value:'good-times', label: 'Good Times'},
  { value:'atmosphere', label: 'Atmosphere'},
  { value:'calm', label: 'Calm'},
  { value:'rocky-landscape', label: 'Rocky Landscape'},
  { value:'lakes', label: 'Lakes'},
  { value:'greener', label: 'Greener'},
  { value:'south-america', label: 'South America'},
  { value:'andes', label: 'Andes'}
]